"""create session_status table

Revision ID: ee9b671d043f
Revises: dcec84f94b0c
Create Date: 2026-03-06 11:37:29.053527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9b671d043f'
down_revision: Union[str, Sequence[str], None] = 'dcec84f94b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_status',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('genome', sa.String(length=10), nullable=False),
    sa.Column('variant_count', sa.Integer(), nullable=False),
    sa.Column('annotated_count', sa.Integer(), nullable=False),
    sa.Column('vcf_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=36), nullable=True),
    sa.Column('queue_name', sa.String(length=10), nullable=True),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_celery_task_id', 'session_status', ['celery_task_id'], unique=False)
    op.create_index('idx_created_at', 'session_status', ['created_at'], unique=False)
    op.create_index('idx_expires_at', 'session_status', ['expires_at'], unique=False)
    op.create_index('idx_status', 'session_status', ['status'], unique=False)
    op.create_index('idx_vcf_hash', 'session_status', ['vcf_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vcf_hash', table_name='session_status')
    op.drop_index('idx_status', table_name='session_status')
    op.drop_index('idx_expires_at', table_name='session_status')
    op.drop_index('idx_created_at', table_name='session_status')
    op.drop_index('idx_celery_task_id', table_name='session_status')
    op.drop_table('session_status')
    # ### end Alembic commands ###
